{"Status":"ERROR!! File \"C:\\Users\\shulc\\anaconda3\\lib\\site-packages\\googlemaps\\client.py\", line 342, in _get_body: [ApiError] REQUEST_DENIED","App_Case_No":"ABC13DEF_8454","Comp_Tel":"0225852516","Comp_Nme":"Âå°|","GMap_Tel_Check":"ERROR","GMap_URL":"ERROR","GMap_Site":"ERROR","GMap_Add":"ERROR","GMap_Tel":"ERROR","GMap_Distance":"ERROR","GMap_Score":"ERROR"}